// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: tvoc

#ifndef _TVOC_UI_H
#define _TVOC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Load
void ui_Load_screen_init(void);
extern void read_scd4x_data(lv_timer_t * timer);
static lv_timer_t* sensor_timer;
void ui_event_Load(lv_event_t * e);
extern lv_obj_t * ui_Load;
extern lv_obj_t * ui_Container;
extern lv_obj_t * ui_Oizom;
// CUSTOM VARIABLES

// SCREEN: ui_TVOC
void ui_TVOC_screen_init(void);
void ui_event_TVOC(lv_event_t * e);
extern lv_obj_t * ui_TVOC;
extern lv_obj_t * ui_Container1;
void ui_event_Arc(lv_event_t * e);
extern lv_obj_t * ui_Arc;
void ui_event_Value(lv_event_t * e);
// Add this line
void update_tvoc_screen(float co2_value, float temperature, float humidity);
extern lv_obj_t * ui_Value;
extern lv_obj_t * ui_CO2;
extern lv_obj_t * ui_CO2Unit;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_TempValue;
extern lv_obj_t * ui_HumidValue;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_oizom_logo_png);    // assets/oizom_logo.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
