// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: tvoc

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Load
void ui_Load_screen_init(void);
void ui_event_Load(lv_event_t * e);
lv_obj_t * ui_Load;
lv_obj_t * ui_Container;
lv_obj_t * ui_Oizom;
// CUSTOM VARIABLES


// SCREEN: ui_TVOC
void ui_TVOC_screen_init(void);
void ui_event_TVOC(lv_event_t * e);
lv_obj_t * ui_TVOC;
lv_obj_t * ui_Container1;
void ui_event_Arc(lv_event_t * e);
lv_obj_t * ui_Arc;
void ui_event_Value(lv_event_t * e);
lv_obj_t * ui_Value;
lv_obj_t * ui_CO2;
lv_obj_t * ui_CO2Unit;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_TempValue;
lv_obj_t * ui_HumidValue;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

// Event handler for the Load screen
void ui_event_Load(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Directly load the TVOC screen on button click
        lv_disp_load_scr(ui_TVOC);
    }
}

// Event handler for the TVOC screen
void ui_event_TVOC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Directly load the Load screen on button click
        lv_disp_load_scr(ui_Load);
    }
}

// Event handler for the Arc (optional functionality)
void ui_event_Arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_Arc, 1);
    }
}

// Event handler for the Value (optional functionality)
void ui_event_Value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_Arc, 1);
    }
}

///////////////////// SCREENS ////////////////////
void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // Initialize both screens
    ui_Load_screen_init();
    ui_TVOC_screen_init();

    // Set up initial actions if needed
    ui____initial_actions0 = lv_obj_create(NULL);

    // Load the initial screen (Load screen)
    lv_disp_load_scr(ui_Load);
}
