// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: tvoc
#include "lvgl.h"
#include "ui.h"

extern void read_scd4x_data(lv_timer_t * timer);

static lv_timer_t* sensor_timer = NULL;

static void go_to_tvoc_screen(lv_timer_t * timer) {

    lv_disp_load_scr(ui_TVOC);

    // Create the sensor update timer (only once)
    if (sensor_timer == NULL) {
        sensor_timer = lv_timer_create(read_scd4x_data, 1000, NULL); 
    }

    read_scd4x_data(NULL);  // immediate update
}

void ui_Load_screen_init(void)
{
    ui_Load = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Load, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container = lv_obj_create(ui_Load);
    lv_obj_remove_style_all(ui_Container);
    lv_obj_set_width(ui_Container, 240);
    lv_obj_set_height(ui_Container, 280);
    lv_obj_set_align(ui_Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Oizom = lv_img_create(ui_Load);
    lv_img_set_src(ui_Oizom, &ui_img_oizom_logo_png);
    lv_obj_set_width(ui_Oizom, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_Oizom, LV_SIZE_CONTENT);    /// 220
    lv_obj_set_align(ui_Oizom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Oizom, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Oizom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Load, ui_event_Load, LV_EVENT_ALL, NULL);

    // Start a timer to go to TVOC screen after 3 seconds (3000 ms)
    lv_timer_create(go_to_tvoc_screen, 3000, NULL);

}
